// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Reviews []*Review `json:"reviews,omitempty"`
}

type Game struct {
	ID        string      `json:"id"`
	Series    *Series     `json:"series,omitempty"`
	Name      string      `json:"name"`
	Platforms []*Platform `json:"platforms,omitempty"`
	Reviews   []*Review   `json:"reviews,omitempty"`
}

type Platform struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Company string  `json:"company"`
	Games   []*Game `json:"games,omitempty"`
}

type Query struct {
}

type Review struct {
	ID      string  `json:"id"`
	Title   string  `json:"title"`
	Content string  `json:"content"`
	Rating  int     `json:"rating"`
	Author  *Author `json:"author"`
	Game    *Game   `json:"game"`
}

type Series struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Games []*Game `json:"games"`
}
